### PR TITLE
Fixed Y Axis flip. This time for reals!

### LINKED ISSUE #55: 3D map is mirrored to the galaxymap ingame
the 3D map has not the same presentation of the galaxy as the galaxymap ingame. It is mirrored over the horizontal layer.
So in my understanding the 3D map shows the inverse of the y values of the star coordinates

### PR DESCRIPTION
**Pull request by gregmalcolm**
Fixes #55

### CODE REVIEW

File: EDDiscovery/3DMap/FormMap.cs [hunk 1]
```diff
@@ -571,19 +571,34 @@ private void Render()
             GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
 
             GL.MatrixMode(MatrixMode.Modelview);
-            GL.LoadIdentity();
-            GL.Rotate(90.0, 1, 0, 0);
+            TransformWorldOrientatation();
+
+            TransformCamera();
+            FlipYAxisOnWorld();
```
Comment (gregmalcolm) [inline EDDiscovery/3DMap/FormMap.cs]: ^This is the only thing that really changed. I just cleaned up a bit by extracting chunks of transformation code into functions as a form of in-built documentation.
